### ISSUE TITLE
Parallel Robots

### ISSUE THREAD

**Issue by progtologist** [ros/robot_model#27]
" The main limitation at this point is that only tree structures can be represented, ruling out all parallel robots."

This issue is more of a wish.
I believe that it is time to integrate parallel robots in the URDF models and ROS in general.

**Comment by DLu** [comment]
I concur with this, but there are a couple important questions. Besides just finding a way to integrate parallel robots into the format, what applications would you like to see?

**Comment by progtologist** [comment]
Personally, I would use it to model a mobile manipulator that we are building for participation in Robocup Rescue, which has a parallel mechanism attached to the tracks of the platform.
In general however, I do believe that stewart platforms and delta robots are very common in research and industry and ROS should be able to provide functionality for those as well.

**Comment by DLu** [comment]
Sorry, I should have been more specific. What applications of the URDF would you like to see? MoveIt? RobotStatePublisher? Drivers?

**Comment by progtologist** [comment]
All core functionality should be incorporated in the URDF, otherwise there is no reason to use ROS all together. It's about not recycling code! Kinematics, Dynamics, motion planning etc

**Comment by fmina** [comment]
Any plan to include parallel robots in URDF soon ?

**Comment by gkjohnson** [comment]
I'm also interested in this. Any updates? Is Github the right place for discussions like this or is there a more active forum elsewhere?

**Comment by sloretz** [comment]
Hi @gkjohnson. I think it may be more productive to start a conversation about parallel robots in URDF in the `Robot Description Formats` [category on discourse.ros.org](https://discourse.ros.org/c/robot-description-formats).

It's difficult to have the conversation on github because `URDF` is so spread out. There needs to be agreement in all of them before one can implement a feature. Maybe a design discussion discourse could turn into a  [REP](http://www.ros.org/reps/rep-0000.html) for URDF?

**Comment by clalancette** [comment]
I'm actually going to close this out in anticipation of archiving this repository.  Please feel free to follow some of the previous advice and open a thread either on discourse or a REP for multiple robots.
