### ISSUE TITLE
collada_dom 2.4 on gentoo

### ISSUE THREAD

**Issue by Antagonistic** [ros/robot_model#72]
While installing collada_parser package, I ran into an odd error where it failed compiling beause it could not find collada_dom's dae.h file (no longer have the exact backlog, sorry)

the location of this file on my system is:

```
/usr/include/collada-dom2.4/dae.h
```

I fixed this by changing line 20 of src/robot_model/collada_parser/CMakeLists.txt from:

```
find_package(COLLADA_DOM 2.3 COMPONENTS 1.5)
```

to 

```
find_package(COLLADA_DOM 2.4 COMPONENTS 1.5)
```

As an aside, this likely needs a REQUIRED or something.

**Comment by tawituthai** [comment]
Wow thanks, I have the same problem just now.

**Comment by jackieokay** [comment]
Hmm. The collada-dom version number could probably get bumped since the system default on trusty is 2.4. I guess the debian on Ubuntu configures the package such that CMake finds version 2.4 if 2.3 is requested. I think it's safe for me to bump the version number for indigo-devel and subsequent releases. Regardless, I should certainly add REQUIRED to this find_package call--I don't see how collada-dom could possibly be optional for this package.

**Comment by ThotAlion** [comment]
I had the same issue to install Colloda on Raspbian. I switched to version 2.4.

**Comment by sloretz** [comment]
Thanks for the issue! `collada_parser` has been moved to a new repository. I've copied the issue to ros/collada_urdf#5
